### ISSUE TITLE
Prevents creating HTML code for images dragged into the editor

### ISSUE THREAD

**Issue by heathflohre** [biati-digital/nova-text-tools#8]
Contacted Panic about the same issue with Emmet, but the plugin blocks Nova's functionality to create an img tag for image files dragged into the editor. It reverts it to the file path. Usually the tag is created immediately, but with the plugin active, there is a slight pause before the path is inserted.

**Comment by biati-digital** [comment]
How can this extension block Nova's functionality? all commands are only executed from the command palette/right click, etc. Dragging a file should not invoke this extension at all.

**Comment by heathflohre** [comment]
Agreed. Panic was alerted as well and they can recreate the bug. The Emmet extension has the same issue when the auto-complete preference is selected. Does your plugin do any active watching of the text?

**Comment by biati-digital** [comment]
I'll try to recreate this issue, it's been a few months since i worked on this so i've to recheck the code and i found myself switching to vscode a lot. 

I'll take a look at this when i've some free time.

**Comment by biati-digital** [comment]
@heathflohre i did some tests, this has to be a bug with Nova, expand selection uses **onDidChangeSelection** to  reset the expand selection history, there's no problems with that code. 

onDidChangeSelection will call maybeResetHistory and this function asks Nova for the current selection with [textEditor.selectedRanges;](https://docs.nova.app/api-reference/text-editor/#selectedranges) this line is the one causing the problem, removing that line solves this problem.

I could try to implement a fix, but this needs to be addressed by Panic because as you mention, the emmet extension also has this problem.

https://user-images.githubusercontent.com/1219228/145690687-4dd0050d-3890-4d80-b76f-4657836d5599.mp4

**Comment by biati-digital** [comment]
Closing as this is something Nova should take a look and fix.
